#!/bin/sh
# PostToolUse(Bash): after `orca worktree create`, remind the master session that it owns the child end to end.
cmd=$(jq -r '.tool_input.command // empty')
case "$cmd" in
  *"orca worktree create"*) ;;
  *) exit 0 ;;
esac
ctx='[orca-child-control] The master session controls this child worktree itself; never hand approval or follow-ups back to the user.
1. If the agent terminal is not started yet: `orca orchestration run-create --objective "<text>" --json` (or reuse `run-current`), then start the terminal with the model and effort the user chose: `orca terminal create --worktree name:<name> --title agent --command "<cli> <model/effort flags>"` (Claude: `claude --dangerously-skip-permissions --model <model> --effort <level>`; Codex: `codex -a never -s workspace-write --add-dir <worktree git dir> -c sandbox_workspace_write.network_access=true -m <model> -c model_reasoning_effort=<level>`, where <worktree git dir> is the output of `git -C <worktree> rev-parse --absolute-git-dir`; the Codex --terminal binding is not verified yet), wait until it is ready with `orca terminal wait --terminal <handle> --for tui-idle --timeout-ms 120000`, then bind it as a dispatched worker instead of sending the prompt: `orca orchestration task-create --run <run_id> --task-title "<topic>" --spec "Read <absolute prompt-file path> and execute it." --json` followed by `orca orchestration worker-start --run <run_id> --task <task_id> --terminal <handle> --worktree name:<name> --json`. Find the agent terminal handle with `orca terminal list --worktree name:<name>`.
2. Keep exactly one background `orca orchestration check --run <run_id> --wait --types question,escalation,worker_done --timeout-ms 600000 --json` running (run_in_background) while the child is active; never end a master turn without it. On `question`, reply with `orca orchestration reply --id <msg_id> --body "..."` (decisions outside the approved plan go to the user). On `escalation`, read it, decide, and reply or correct with `orca terminal send`. On `worker_done`, acknowledge it once without waiting (`orca orchestration check --run <run_id> --ack <deliveryId> --json`) so the next task on the same Run does not receive a stale replay of it, then go to step 3. On timeout (no message in 10 minutes), run `worker-show --dispatch <id>`, `orca terminal read --terminal <handle> --screen | tail`, and check the `TASKS.md` mtime; unblock with `orca terminal send` if the child is parked on a human-only prompt, stuck in a foreground command, or idle without a report, otherwise do nothing. After every wake-up, re-arm the background `check` with `--ack <deliveryId>` of the batch just handled, in every branch including timeout.
3. The `worker_done` body is the five-line report; a `worker_done --outcome failed` is handled like a report with a blocker. Check the verification line first; if it has no evidence (commands run + output), send it back. Then do the final review in the master: `git -C <worktree> status --short` and `git -C <worktree> diff` against the declared scope. List only problems that would block the merge, each with file:line, why it is wrong, and how to show it fails. For large diffs, delegate the diff read to a reviewer subagent to save master context. Send fixes back to the child if needed. After a rebase that moved the base, have the child rerun verification.
4. Commit and ship from the master: `git -C <worktree> add -A && git -C <worktree> commit`, `git fetch origin && git -C <worktree> rebase origin/master` (rerun the required tests in the child if the base moved), `git merge --ff-only <branch>` in the master checkout, `git push origin master`.
5. Clean up: `orca orchestration worker-release --dispatch <id>` (returns `retained` for a terminal bound with --terminal, and closes nothing), then `orca worktree rm --worktree name:<name>` to actually close the terminal.'
jq -n --arg ctx "$ctx" '{hookSpecificOutput:{hookEventName:"PostToolUse",additionalContext:$ctx}}'
